spring.application.name=escola-api
spring.devtools.restart.enabled=false
spring.jackson.serialization.fail-on-empty-beans=false

spring.config.import=classpath:configs/database.properties
spring.devtools.restart.enabled=false
spring.jackson.serialization.fail-on-empty-beans=false

spring.config.import=classpath:configs/database.properties